export const teamMembers = [
  {
    id: 1,
    name: "Abubakar Ibrahim",
    role: "Founder & Executive Director",
    shortBio: "Passionate about empowering the next generation of leaders through education and mentorship.",
    fullBio: "Abubakar founded Johnnie Boy's Foundation with a vision to create lasting change in the lives of boys and young men across northern Nigeria. With over 15 years of experience in community development and youth empowerment, he has dedicated his life to building programs that help young people discover their potential and become leaders who create positive change. His approach combines education, mentorship, and practical skills training to address the unique challenges facing boys in underserved communities.",
    email: "abubakar@johnnieboysfoundation.org",
    social: { linkedin: "#", twitter: "#" },
  },
  {
    id: 2,
    name: "Fatima Abdullahi",
    role: "Program Director",
    shortBio: "Designs and oversees all foundation programs, ensuring maximum impact for every participant.",
    fullBio: "Fatima brings a wealth of experience in program management and youth development. She oversees the design, implementation, and evaluation of all foundation programs, from mentorship to skills training. Her data-driven approach ensures that every program delivers measurable results while maintaining the personal touch that makes each participant feel valued. Fatima holds a Master's degree in Social Work and has worked with leading youth organizations across West Africa.",
    email: "fatima@johnnieboysfoundation.org",
    social: { linkedin: "#", twitter: "#" },
  },
  {
    id: 3,
    name: "Ibrahim Musa",
    role: "Head of Education",
    shortBio: "Leads educational initiatives, scholarships, and school support programs for boys.",
    fullBio: "Ibrahim is the heart behind our education programs. He manages scholarships, learning materials distribution, and school support systems that help boys stay in school and excel academically. With a background in education policy and curriculum development, Ibrahim has helped hundreds of students access quality education and develop the academic skills they need to succeed. He believes every boy deserves the opportunity to learn and grow.",
    email: "ibrahim@johnnieboysfoundation.org",
    social: { linkedin: "#", twitter: "#" },
  },
  {
    id: 4,
    name: "Aisha Bello",
    role: "Mentorship Coordinator",
    shortBio: "Connects mentors with mentees, building relationships that transform lives.",
    fullBio: "Aisha manages our mentorship program, carefully matching mentors with young men who need guidance and support. She trains mentors, monitors relationships, and ensures that every pairing leads to meaningful growth. Her intuitive understanding of young people's needs and her ability to build trust have made the mentorship program one of our most impactful initiatives. Aisha holds a degree in Psychology and has specialized training in youth counseling.",
    email: "aisha@johnnieboysfoundation.org",
    social: { linkedin: "#", twitter: "#" },
  },
  {
    id: 5,
    name: "Yusuf Danjuma",
    role: "Skills Training Lead",
    shortBio: "Develops and delivers practical skills programs in technology, creativity, and vocation.",
    fullBio: "Yusuf leads our skills training programs, teaching boys practical digital, creative, and vocational skills that open doors to future careers. From coding workshops to creative arts sessions, he designs curriculum that is both engaging and relevant to today's job market. With a background in software development and vocational training, Yusuf has helped young men gain the skills they need to become self-sufficient and successful.",
    email: "yusuf@johnnieboysfoundation.org",
    social: { linkedin: "#", twitter: "#" },
  },
  {
    id: 6,
    name: "Hauwa Suleiman",
    role: "Wellness Counselor",
    shortBio: "Provides emotional support and counseling services for boys and their families.",
    fullBio: "Hauwa is the compassionate voice behind our wellness programs. She provides individual and group counseling, helping boys process their emotions, build resilience, and develop emotional strength. Her work extends to families, helping parents and guardians understand how to support their children's emotional development. Hauwa is a licensed counselor with specialized training in trauma-informed care and adolescent psychology.",
    email: "hauwa@johnnieboysfoundation.org",
    social: { linkedin: "#", twitter: "#" },
  },
  {
    id: 7,
    name: "Khalid Abubakar",
    role: "Community Outreach Manager",
    shortBio: "Builds partnerships and connects the foundation with communities across northern Nigeria.",
    fullBio: "Khalid is the bridge between our foundation and the communities we serve. He manages outreach programs, builds partnerships with local organizations, and ensures that our programs reach the boys who need them most. His deep connections within communities and his understanding of local dynamics make him invaluable in expanding our reach. Khalid has a background in community development and public relations.",
    email: "khalid@johnnieboysfoundation.org",
    social: { linkedin: "#", twitter: "#" },
  },
  {
    id: 8,
    name: "Maryam Aliyu",
    role: "Communications Director",
    shortBio: "Tells the foundation's story and raises awareness about our mission and impact.",
    fullBio: "Maryam leads all communications efforts, from social media to press relations to impact reporting. She ensures that the foundation's story reaches a wide audience and that our impact is clearly communicated to stakeholders, donors, and the public. With a background in journalism and digital marketing, Maryam has helped raise the foundation's profile and attract support from individuals and organizations across the country.",
    email: "maryam@johnnieboysfoundation.org",
    social: { linkedin: "#", twitter: "#" },
  },
];
